#MakeFile
#Generates a file to define what the following commands do:
#	*make:	general compilation of the project
#	*make unittest:	compilation of unit tests
#	*make run:	executes primary program
#	*make run_unittest:executes unit tests

#Created by:
#Erick Obando Solano B14757


#Declaration of Variables

#Compiler
CC = g++

#Compiler flags
CFLAGS = -Wall -g -std=c++14


#Directories where files are located

# Include directory
IDIR = -I ../include/

# SRC directory
SRCDIR =  ../src/

# TEST directory
TESTDIR = -I ../test/

# TEST directory
MISCDIR =  ../misc/

#Targets requiered (executables)
#SRC targets
SRC=main.o avltree_get_data.o avltree_functions.o
#INCLUDEOBJECTS=avltree_functions avltree_get_data

#TEST targets
OBJECTS = main.o AVL.o avltree_ObtainData.o
TESTOBJECTS = testmain.o test.o  AVL.o
#Rules
#*List of object to compile all .cpp files
all :  $(SRC)
#		*Generation command
	$(CC) $(CFLAGS) $(IDIR) -o output.out $(SRC)
#	$(CC) $(CFLAGS) -o output
$(SRC) :
	$(CC) $(CFLAGS) $(SCRDIR) -c $@.cpp

#Execute the output of the compilation generated by make command
run: $(SRC)
	./output.out

unittest: $(TESTOBJECTS)
	#		*Generation command
	$(CC) $(CFLAGS) $(TESTDIR) $(TESTOBJECTS) -o outputTest
	#	$(CC) $(CFLAGS) -o output
	$(CC) $(CFLAGS) $(TESTDIR) -c $@.cpp

	#Execute the output of the compilation generated by make command
run_unittest: $(TESTOBJECTS) $(OBJECTS)
	./outputTest
